- name: deploy cert-manager
  k8s:
    definition: "{{ item }}"
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: "{{ k8s_manifests_state }}"
    force: "{{ k8s_force }}"
  loop: 
    - "{{ lookup('template', k8s_manifests_base_dir + 'cert-manager/namespace.yaml') | from_yaml_all | list }}"
    - "{{ lookup('template', k8s_manifests_base_dir + 'cert-manager/cert-manager.yaml') | from_yaml_all | list }}"
    - "{{ lookup('template', k8s_manifests_base_dir + 'cert-manager/letsencrypt-clusterissuer.yaml') | from_yaml_all | list }}"
  register: k8s_result
  until: k8s_result is success
  retries: 10
  delay: 10
  no_log: "{{ k8s_no_log }}"
  