#jinja2: trim_blocks:False
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
{% for user in map_users.system_masters %}
    - userarn: "{{ user.arn }}"
      username: "{{ user.name }}"
      groups:
        - system:masters
{% endfor %}
  mapRoles: |
{% for role in map_roles.workers_roles %}
    - rolearn: "{{ role }}"
      username: {% raw -%} "system:node:{{ '{{' }}EC2PrivateDNSName{{ '}}' }}" {%- endraw %}
      groups:
        - system:bootstrappers
        - system:nodes
{% endfor %}
{% for role in map_roles.system_masters %}
    - rolearn: "{{ role }}"
      username: {% raw -%} "admin:{{ '{{' }}SessionName{{ '}}' }}" {%- endraw %}
      groups:
        - system:masters
{% endfor %}
